name: firestore_interop
description: Dart facade for Cloud Firestore NodeJS client library.
version: 0.0.1
homepage: https://www.github.com/pulyaevskiy/firestore-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.1
  func: ^1.0.0
  node_interop: '>=0.1.0-beta.4 <0.2.0'

dev_dependencies:
  test: ^0.12.24

transformers:
  - $dart2js
  - node_interop
