name: firestore_interop
description: Dart facade for Cloud Firestore NodeJS client library.
version: 1.0.0-dev.1.0
homepage: https://www.github.com/pulyaevskiy/firestore-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev.19.0 <2.0.0'

dependencies:
  js: ^0.6.1
  func: ^1.0.0
  node_interop:
    git: 
      url: git@github.com:pulyaevskiy/node-interop.git
      ref: dart20

dev_dependencies:
  test: ^0.12.24
